import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// import { Inter } from "next/font/google";
// import styles from "styles/globals.css";
// const canvas = document.getElementById("myCanvas");
// const ctx = canvas.getContext("2d");
// ctx.beginPath();
// ctx.rect(20, 20, 150, 100);
// ctx.stroke();

export default function Home() {
  return (
    <>
      <div
        style={{
          // backgroundColor: "mediumpurple",
          padding: "0.8rem",
        }}
        className={styles.bg}
      >
        <div className="hstack gap-5">
          {/* <Image
            src="lib/img/cmul.JPG"
            alt=""
            width="250"
            height="100"
            className="relative"
          /> */}
          <span
            style={{
              marginLeft: "50px",
              fontSize: "30px",
              fontWeight: "bold",
            }}
          >
            Chiang Mai University Library
          </span>
          <Link href="/login">
            <span style={{ marginLeft: "900px" }}>Staff login</span>
          </Link>
        </div>
      </div>

      {/* <div className="floor" style={{ padding: "0.5rem" }}>
        <button style={{ border: "round" }}>1st Floor</button>
      </div> */}
      <div
        className={styles.border}
        style={{
          // width: "600px",
          // display: "inline-block",
          textAlign: "center",
          marginLeft: "2rem",
          marginRight: "2rem",
          marginTop: "1rem",
          padding: "2rem",
        }}
      >
        {/* <Link href="/index">
          
        </Link> */}
        <h3>1st Floor</h3>

        <Link href="/secondF">
          <h3>2nd Floor</h3>
        </Link>

        <Link href="/thirdF">
          <h3>3rd Floor</h3>
        </Link>

        <Link href="/fourthF">
          <h3>4th Floor</h3>
        </Link>

        <Image
          src="/img/map1.jpg"
          layout="fill"
          objectFit="cover"
          quality={100}
        />
      </div>

      {/* <input>search...</input> */}
    </>
  );
}

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
